Seminar1/Home1/Home1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Home1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('shop.urls')),
    # path('__debug__/',include('debug_toolbar.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Seminar1/Home1/MYRandom/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("one/",views.one, name="one"),
    path("two/",views.two, name="two"),
    path("three/",views.three, name="three"),
]

Seminar1/Home1/shop/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('catalog/', views.catalog, name='catalog'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
    path('order_list/<int:client_id>/', views.order_list, name='order_list'),
    path('create_order/', views.create_order, name='create_order'),
    path('order_success/', views.order_success, name='order_success'),
    path('product_edit/<int:product_id>/', views.product_edit, name='product_edit'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/<int:client_id>/', views.client_detail, name='client_detail'),

]

Seminar1/Home1/MYRandom/models.py
from django.db import models

# Create your models here.

Seminar1/Home1/shop/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.TextField()
    time_create = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'Name: {self.name}, Email: {self.email}, Phone: {self.phone}, Address: {self.address}'


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(blank=True, verbose_name="Описание")
    image = models.ImageField(upload_to="images/", verbose_name="Изображение")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.PositiveIntegerField()
    time_create = models.DateField(auto_now_add=True)

    @property
    def photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
    def __str__(self):
        return f'Title: {self.title}, description: {self.description}, price: {self.price}, amount: {self.amount}'

    def get_full_description(self):
        return f'Title: {self.title}, description: {self.description}, price: {self.price}, amount: {self.amount}'

class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    time_create = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Заказ от {self.client} на сумму {self.total_amount}"

Seminar1/Home1/shop/forms.py
from django import forms

from shop.models import Order, Product


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'products', 'total_amount']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'image', 'price', 'amount']



Seminar1/Home1/MYRandom/views.py
from random import random, choice, randint
import logging

logger = logging.getLogger(__name__)

from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def one(request):
    logger.info("One page started")
    answer = ["Орёл", "Решка"]
    i = choice(answer)
    return HttpResponse(i)


def two(request):
    logger.info("Two page started")
    answer = randint(1, 6)
    return HttpResponse(answer)


def three(request):
    logger.info("Tree page started")
    return HttpResponse(randint(0, 100))

Seminar1/Home1/shop/views.py
import logging
from datetime import timedelta

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.generic import DetailView

from shop.models import Client, Product, Order
from shop.forms import OrderForm, ProductForm

# Create your views here.
logger = logging.getLogger(__name__)
menu = [
    {'title': "Главная", 'url_name': 'home'},
    {'title': "Каталог", 'url_name': 'catalog'},
    {'title': "О нас", 'url_name': 'about'},
    {'title': "Контакты", 'url_name': 'contact'}
]


def index(request):
    logger.info("OK")
    products = Product.objects.all()

    return render(request, 'shop/index.html',{'products':products})


def catalog(request):
    logger.info("catalog")
    products = Product.objects.all()
    total = sum(products.amount for products in products)
    return render(request, 'shop/catalog.html',{'products':products,'total': total})


def about(request):
    logger.info("about")
    return render(request, 'shop/about.html')


def contact(request):
    logger.info("contact")
    return render(request, 'shop/contact.html')


def order_list(request, client_id):
    user_orders = Order.objects.filter(client_id=client_id)
    return render(request, 'shop/order_list.html', {'orders': user_orders})


# Функция создания нового клиента
def create_client(name, email, phone, address):
    client = Client(name=name, email=email, phone=phone, address=address)
    client.save()


# Функция чтения информации о клиенте по его ID
def client_detail(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    return render(request, 'shop/client_detail.html', {'client': client})


def client_list(request):
    clients = Client.objects.all()

    return render(request, 'shop/client_list.html', {'clients': clients})

# Функция обновления информации о клиенте
def update_client(client_id, new_name):
    client = Client.objects.get(id=client_id)
    client.name = new_name
    client.save()


# Функция удаления клиента
def delete_client(client_id):
    client = Client.objects.get(id=client_id)
    client.delete()


# Функция создания нового товара
def create_product(title, description, price, amount):
    product = Product(title=title, description=description, price=price, amount=amount)
    product.save()


# Функция чтения информации о товаре по его ID
def get_product(product_id):
    product = Product.objects.get(id=product_id)
    return product


# Функция обновления информации о товаре
def product_edit(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_detail', product_id=product_id)
    else:
        form = ProductForm(instance=product)

    return render(request, 'shop/product_edit.html', {'form': form})


# Функция удаления товара
def delete_product(product_id):
    product = Product.objects.get(id=product_id)
    product.delete()


# Функция создания нового заказа
def create_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            # Дополнительная обработка данных и создание заказа
            return redirect('order_success')
    else:
        form = OrderForm()

    return render(request, 'shop/order_form.html', {'form': form})

def order_success(request):
    return render(request, 'shop/order_success.html')


# Функция чтения информации о заказе по его ID
def get_order(order_id):
    order = Order.objects.get(id=order_id)
    return order


# Функция обновления информации о заказе
def update_order(order_id, new_total_amount):
    order = Order.objects.get(id=order_id)
    order.total_amount = new_total_amount
    order.save()


# Функция удаления заказа
def delete_order(order_id):
    order = Order.objects.get(id=order_id)
    order.delete()

def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'shop/product_detail.html', {'product': product})

Seminar1/Home1/shop/templates/about.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<body>
<div style="width: 90%; border: 1px solid #333; box-shadow: 8px 8px 5px #444; padding: 8px 12px; background-image: linear-gradient(180deg, #fff, #ddd 40%, #ccc)">
    <h1>Добро пожаловать в наш интернет-магазин!</h1>
</div>
<div class="container">
    <p style="padding: 20px;">Здесь вы найдете широкий выбор качественных товаров по отличным ценам. <br>Наш
        интернет-магазин предлагает разнообразие
        продуктов для всех возрастных категорий и интересов. У нас вы можете найти модную одежду, стильные аксессуары,
        косметику,
        товары для дома, электронику и многое другое. Мы тщательно подбираем товары, чтобы обеспечить высокое качество и
        удовлетворить потребности наших клиентов.</p>
    <p>Независимо от того, что вас интересует - модный стиль, функциональность или красота - наш интернет-магазин
        предлагает
        разнообразие опций для удовлетворения ваших потребностей. Мы постоянно обновляем наш ассортимент, чтобы
        предложить вам новые и новейшие товары.</p>
    <p>Мы стремимся предоставить непревзойденный уровень обслуживания наших клиентов. Наша команда всегда готова помочь
        вам в
        выборе товара, ответить на ваши вопросы и обеспечить приятный опыт покупок в нашем магазине.</p>
    <p>Оформление заказа у нас легкое и безопасное. Мы гарантируем безопасность ваших платежей и конфиденциальность
        вашей информации.</p>
    <p>Мы ценим каждого клиента и стремимся к высокому уровню удовлетворенности. Ваше мнение очень важно для нас,
        поэтому мы
        всегда открыты к обратной связи, предложениям и комментариям.</p>
    <p>Мы приглашаем вас ознакомиться с нашим ассортиментом и найти то, что идеально подойдет именно для вас. Благодарим
        вас за выбор нашего интернет-магазина и желаем вам приятных покупок!</p>
</div>
{% endblock %}

Seminar1/Home1/shop/templates/add_product.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить товар</button>
</form>

Seminar1/Home1/shop/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Название вашего интернет-магазина</title>
</head>
<body style="font-family: Arial, sans-serif;line-height: 1.5;background-color: #f5f5f5;  margin: 0;padding: 0;box-sizing: border-box">
<header style="background-color: #333;padding: 20px;color: #fff;">
    <h1 style="margin-bottom: 10px;">Добро пожаловать в наш интернет-магазин!</h1>
    <nav>
        <ul style="list-style-type: none;">
            <li style="display: inline-block;margin-right: 15px;"><a style="text-decoration: none;color: #fff;"
                                                                     href="{% url 'home' %}">Главная</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration: none;color: #fff;" href="{% url 'catalog' %}">Каталог</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration: none;color: #fff;" href="{% url 'about' %}">О нас</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'contact' %}">Контакты</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'create_order' %}">Сделать заказ</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'order_list' client_id=user.pk %}">Ваш заказ</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'client_list' %}">Все заказы</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'product_edit' product_id=user.pk %}">Редактировать товар</a></li>
        </ul>
    </nav>
</header>
{% block content %}{% endblock %}
<footer style=" background-color: #333;color: #fff;padding: 20px;text-align: center;">
    <p>&copy; 2023 Мой интернет-магазин. Все права принадлежат мне))).</p>
</footer>
</body>
</html>

Seminar1/Home1/shop/templates/catalog.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<h2>Наш ассортимент товаров</h2>
    <ul>
        {% for product in products %}
        <li>
            <h2>{{ product.title }}</h2>
            <img src="{{product.image.url }}">
            {{ product.description|truncatewords:50 }}

            {{ product.price }} руб.
            <div class="clear"></div>
			<p class="link-read-post"><a href="{% url 'product_detail' product_id=product.id %}">Читать пост</a></p>
            <p class="link-read-post"><a href="{% url 'product_edit' product_id=product.id %}">Редактировать товар</a>
</p>

        </li>
        {% endfor %}
    </ul>
{% endblock %}

Seminar1/Home1/shop/templates/client_detail.html
{% extends 'shop/base.html' %}

{% block content %}
  <h1>Детали клиента</h1>

  <p>Имя: {{ client.name }}</p>
  <p>Email: {{ client.email }}</p>
  <!-- Добавьте другие поля объекта клиента, по мере необходимости -->
{% endblock %}

Seminar1/Home1/shop/templates/client_list.html
{% extends 'shop/base.html' %}

{% block content %}
  <h1>Список клиентов</h1>

  <ul>
    {% for client in clients %}
      <li>
        <a href="{% url 'client_detail' client.id %}">{{ client.name }}</a>
        <p>Email: {{ client.email }}</p>
        <p>Адрес: {{ client.address }}</p>

        <ul>
          {% for order in client.order_set.all %}
            <li>
              Заказ: {{ order.id }},
              Итоговая стоимость: {{ order.total_amount }}
            </li>
          {% empty %}
            <li>Нет доступных заказов для этого клиента.</li>
          {% endfor %}
        </ul>

      </li>
    {% empty %}
      <li>Нет доступных клиентов.</li>
    {% endfor %}
  </ul>
{% endblock %}

Seminar1/Home1/shop/templates/contact.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<a href="https://vk.com/odarka_kruk">Darja Krjukova</a>
{% endblock %}

Seminar1/Home1/shop/templates/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<main style="padding: 20px;">
    <section class="banner" style="margin-bottom: 30px; background-color: #f9f9f9;padding: 30px;text-align: center;">
        <h2 style="margin-bottom: 10px;">Акционные предложения!</h2>
        <p style="margin-bottom: 20px;">У нас есть лучшие товары по низким ценам. Поторопитесь сделать заказ!</p>
        <a href="#" class="btn"
           style="display: inline-block;padding: 10px 20px;background-color: #333;color: #fff;text-decoration: none;border-radius: 5px;">Купить
            сейчас</a>
    </section>
    <h2 style="text-align: center;">Популярные товары</h2><br>
    <section class="featured-products" style="display: block;margin-left: auto; margin-right: auto;">

        {% for product in products %}
        <li style="display: block;margin-left: auto; margin-right: auto;">
        <div class="product" style="display: block;width: 25%;padding: 10px;text-align: center;">
                <img src="{{product.image.url }}" alt="Товар в топе" style="width: 100%;max-height: 200px;object-fit: cover;margin-bottom: 10px;">
        <h3 style="margin-bottom: 5px;">{{ product.title}}</h3>
        <p style="margin-bottom: 20px;">{{ product.price}}</p>
        <a href="#" class="btn"
           style="display: inline-block;padding: 10px 20px;background-color: #333;color: #fff;text-decoration: none;border-radius: 5px;">Подробнее</a>
        </div>
</li>
        {% endfor %}
    </section>
</main>
{% endblock %}

Seminar1/Home1/shop/templates/order_form.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<h1>Форма заказа</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>

{% endblock %}

Seminar1/Home1/shop/templates/order_list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
  <h1>Список заказов</h1>

  <table>
    <thead>
      <tr>
        <th>Имя клиента</th>
        <th>Адресс</th>
        <th>Сумма</th>
        <th>Дата создания</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
        <td>{{ order.client.name }}</td>
        <td>{{ order.client.address }}</td>
        <td>{{ order.total_amount }}</td>
        <td>{{ order.time_create }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">Нет доступных заказов.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

Seminar1/Home1/shop/templates/order_success.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<h1>Заказ успешно создан</h1>
    <p>Спасибо за ваш заказ!</p>

{% endblock %}

Seminar1/Home1/shop/templates/product.html
{% extends 'shop/base.html' %}

{% block content %}
<h1>{{product.title}}</h1>

{% if product.image %}
<p><img class="img-article-left" src="{{product.image.url}}"></p>
{% endif %}

{{product.description|linebreaks}}
{% endblock %}

Seminar1/Home1/shop/templates/product_detail.html
{% extends 'shop/base.html' %}

{% block content %}
 <h1>{{ product.title }}</h1>

  <img src="{{ product.image.url }}" alt="{{ product.title }}">

  <p>{{ product.description }}</p>

  <p>Цена: {{ product.price }}</p>

  <p>Количество: {{ product.amount }}</p>

{% endblock %}


Seminar1/Home1/shop/templates/product_edit.html
{% extends 'shop/base.html' %}

{% block content %}
  <h1>Редактировать продукт</h1>
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div>
      <label for="id_title">Название:</label>
      <input type="text" id="id_title" name="title" value="{{ product.title }}">
    </div>
    
    <div>
      <label for="id_description">Описание:</label>
      <textarea id="id_description" name="description">{{ product.description }}</textarea>
    </div>
    
    <div>
      <label for="id_image">Изображение:</label>
      <input type="file" id="id_image" name="image" accept="image/*">
    </div>
    
    <div>
      <label for="id_price">Цена:</label>
      <input type="number" id="id_price" name="price" value="{{ product.price }}">
    </div>
    
    <div>
      <label for="id_amount">Количество:</label>
      <input type="number" id="id_amount" name="amount" value="{{ product.amount }}">
    </div>
    
    <button type="submit">Сохранить</button>
  </form>
  
{% endblock %}

Seminar1/Home1/shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<body>
<div style="width: 90%; border: 1px solid #333; box-shadow: 8px 8px 5px #444; padding: 8px 12px; background-image: linear-gradient(180deg, #fff, #ddd 40%, #ccc)">
    <h1>Добро пожаловать в наш интернет-магазин!</h1>
</div>
<div class="container">
    <p style="padding: 20px;">Здесь вы найдете широкий выбор качественных товаров по отличным ценам. <br>Наш
        интернет-магазин предлагает разнообразие
        продуктов для всех возрастных категорий и интересов. У нас вы можете найти модную одежду, стильные аксессуары,
        косметику,
        товары для дома, электронику и многое другое. Мы тщательно подбираем товары, чтобы обеспечить высокое качество и
        удовлетворить потребности наших клиентов.</p>
    <p>Независимо от того, что вас интересует - модный стиль, функциональность или красота - наш интернет-магазин
        предлагает
        разнообразие опций для удовлетворения ваших потребностей. Мы постоянно обновляем наш ассортимент, чтобы
        предложить вам новые и новейшие товары.</p>
    <p>Мы стремимся предоставить непревзойденный уровень обслуживания наших клиентов. Наша команда всегда готова помочь
        вам в
        выборе товара, ответить на ваши вопросы и обеспечить приятный опыт покупок в нашем магазине.</p>
    <p>Оформление заказа у нас легкое и безопасное. Мы гарантируем безопасность ваших платежей и конфиденциальность
        вашей информации.</p>
    <p>Мы ценим каждого клиента и стремимся к высокому уровню удовлетворенности. Ваше мнение очень важно для нас,
        поэтому мы
        всегда открыты к обратной связи, предложениям и комментариям.</p>
    <p>Мы приглашаем вас ознакомиться с нашим ассортиментом и найти то, что идеально подойдет именно для вас. Благодарим
        вас за выбор нашего интернет-магазина и желаем вам приятных покупок!</p>
</div>
{% endblock %}

Seminar1/Home1/shop/templates/shop/add_product.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить товар</button>
</form>

Seminar1/Home1/shop/templates/shop/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Название вашего интернет-магазина</title>
</head>
<body style="font-family: Arial, sans-serif;line-height: 1.5;background-color: #f5f5f5;  margin: 0;padding: 0;box-sizing: border-box">
<header style="background-color: #333;padding: 20px;color: #fff;">
    <h1 style="margin-bottom: 10px;">Добро пожаловать в наш интернет-магазин!</h1>
    <nav>
        <ul style="list-style-type: none;">
            <li style="display: inline-block;margin-right: 15px;"><a style="text-decoration: none;color: #fff;"
                                                                     href="{% url 'home' %}">Главная</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration: none;color: #fff;" href="{% url 'catalog' %}">Каталог</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration: none;color: #fff;" href="{% url 'about' %}">О нас</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'contact' %}">Контакты</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'create_order' %}">Сделать заказ</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'order_list' client_id=user.pk %}">Ваш заказ</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'client_list' %}">Все заказы</a></li>
            <li style="display: inline-block;margin-right: 15px;"><a  style="text-decoration:none;color:#fff;" href="{% url 'product_edit' product_id=user.pk %}">Редактировать товар</a></li>
        </ul>
    </nav>
</header>
{% block content %}{% endblock %}
<footer style=" background-color: #333;color: #fff;padding: 20px;text-align: center;">
    <p>&copy; 2023 Мой интернет-магазин. Все права принадлежат мне))).</p>
</footer>
</body>
</html>

Seminar1/Home1/shop/templates/shop/catalog.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<h2>Общее число товаров: {{ total }}</h2>
<h2>Наш ассортимент товаров</h2>
    <ul>
        {% for product in products %}
        <li>
            <h2>{{ product.title }}</h2>
            <img src="{{product.image.url }}">
            {{ product.description|truncatewords:50 }}

            {{ product.price }} руб.
            <div class="clear"></div>
			<p class="link-read-post"><a href="{% url 'product_detail' product_id=product.id %}">Читать пост</a></p>
            <p class="link-read-post"><a href="{% url 'product_edit' product_id=product.id %}">Редактировать товар</a>
</p>

        </li>
        {% endfor %}
    </ul>
{% endblock %}

Seminar1/Home1/shop/templates/shop/client_detail.html
{% extends 'shop/base.html' %}

{% block content %}
  <h1>Детали клиента</h1>

  <p>Имя: {{ client.name }}</p>
  <p>Email: {{ client.email }}</p>
  <!-- Добавьте другие поля объекта клиента, по мере необходимости -->
{% endblock %}

Seminar1/Home1/shop/templates/shop/client_list.html
{% extends 'shop/base.html' %}

{% block content %}
  <h1>Список клиентов</h1>

  <ul>
    {% for client in clients %}
      <li>
        <a href="{% url 'client_detail' client.id %}">{{ client.name }}</a>
        <p>Email: {{ client.email }}</p>
        <p>Адрес: {{ client.address }}</p>

        <ul>
          {% for order in client.order_set.all %}
            <li>
              Заказ: {{ order.id }},
              Итоговая стоимость: {{ order.total_amount }}
            </li>
          {% empty %}
            <li>Нет доступных заказов для этого клиента.</li>
          {% endfor %}
        </ul>

      </li>
    {% empty %}
      <li>Нет доступных клиентов.</li>
    {% endfor %}
  </ul>
{% endblock %}

Seminar1/Home1/shop/templates/shop/contact.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<a href="https://vk.com/odarka_kruk">Darja Krjukova</a>
{% endblock %}

Seminar1/Home1/shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<main style="padding: 20px;">
    <section class="banner" style="margin-bottom: 30px; background-color: #f9f9f9;padding: 30px;text-align: center;">
        <h2 style="margin-bottom: 10px;">Акционные предложения!</h2>
        <p style="margin-bottom: 20px;">У нас есть лучшие товары по низким ценам. Поторопитесь сделать заказ!</p>
        <a href="#" class="btn"
           style="display: inline-block;padding: 10px 20px;background-color: #333;color: #fff;text-decoration: none;border-radius: 5px;">Купить
            сейчас</a>
    </section>
    <h2 style="text-align: center;">Популярные товары</h2><br>
    <section class="featured-products" style="display: block;margin-left: auto; margin-right: auto;">

        {% for product in products %}
        <li style="display: block;margin-left: auto; margin-right: auto;">
        <div class="product" style="display: block;width: 25%;padding: 10px;text-align: center;">
                <img src="{{product.image.url }}" alt="Товар в топе" style="width: 100%;max-height: 200px;object-fit: cover;margin-bottom: 10px;">
        <h3 style="margin-bottom: 5px;">{{ product.title}}</h3>
        <p style="margin-bottom: 20px;">{{ product.price}}</p>
        <a href="#" class="btn"
           style="display: inline-block;padding: 10px 20px;background-color: #333;color: #fff;text-decoration: none;border-radius: 5px;">Подробнее</a>
        </div>
</li>
        {% endfor %}
    </section>
</main>
{% endblock %}

Seminar1/Home1/shop/templates/shop/order_form.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}

<h1>Форма заказа</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>

{% endblock %}

Seminar1/Home1/shop/templates/shop/product_edit.html
{% extends 'shop/base.html' %}

{% block content %}
  <h1>Редактировать продукт</h1>
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div>
      <label for="id_title">Название:</label>
      <input type="text" id="id_title" name="title" value="{{ product.title }}">
    </div>
    
    <div>
      <label for="id_description">Описание:</label>
      <textarea id="id_description" name="description">{{ product.description }}</textarea>
    </div>
    
    <div>
      <label for="id_image">Изображение:</label>
      <input type="file" id="id_image" name="image" accept="image/*">
    </div>
    
    <div>
      <label for="id_price">Цена:</label>
      <input type="number" id="id_price" name="price" value="{{ product.price }}">
    </div>
    
    <div>
      <label for="id_amount">Количество:</label>
      <input type="number" id="id_amount" name="amount" value="{{ product.amount }}">
    </div>
    
    <button type="submit">Сохранить</button>
  </form>
  
{% endblock %}